### ISSUE TITLE
FAIL - Application at context path /openhds could not be started

### ISSUE THREAD

**Issue by killamorriz** [SwissTPH/openhds#2]
after deploying the war file i get the above error... then when i start openhgs i get
FAIL - Application at context path /openhds could not be started

 tomcat logs says--

Caused by: org.hibernate.HibernateException: Connection cannot be null when 'hibernate.dialect' not set

**Comment by aurdipas** [comment]
please follow the installation process properly. The message is related to a wrong configuration of the database.
