### ISSUE TITLE
asking for data dictionary

### ISSUE THREAD

**Issue by alazarbaharu** [SwissTPH/openhds#3]
Hello Dear OpenHds Team this is alazar From Arba Minch Hdss Data manager and i have two questions to ask related to openhds one is we have migrated the data from hrs2 to open hds sucessfully and when i see the outcome table it is only showing data for the uuid column and type but the childextId, child_uuid and childMembership_uuid shows null so what is the problem with it or it has to be like that.
My second question is to get database dictionary for all attributes and table if there is, i searched over the internet then i found the database schema in the google group but it is showing information about the tables attributes data type size and indexes but what i need is textual description for all database tables and there attributes if possible. Thanks for your support

**Comment by aurdipas** [comment]
Dear alazarbaharu this is not the correct place for requests. Please write to openhds@unibas.ch and you'll get the requested information. I'm going to close this issue. Regards
